version: '3.8'

services:
  python-service:
    build: ./python-service
    container_name: python-service
    ports:
      - "8000:8000"
    networks:
      - elk-net

  go-service:
    build: ./go-service
    container_name: go-service
    ports:
      - "8083:8080"
    networks:
      - elk-net

  rust-service:
    build: ./rust-service
    container_name: rust-service
    ports:
      - "8081:8081"
    networks:
      - elk-net

  java-service:
    build: ./java-service
    container_name: java-service
    ports:
      - "8082:8082"
    networks:
      - elk-net

networks:
  elk-net:
    driver: bridge
